---

name: Build on various Operating Systems

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JACK2_VERSION: v1.9.22
  MESON_LINUX_BUILD_OPTS: --prefix=/usr
  PAWPAW_CACHE_VERSION: 1
  PAWPAW_JACK2_NO_CUSTOM_PREFIX: 1
  PAWPAW_SKIP_LTO: 1
  PAWPAW_VERSION: c630bae2e77c210c7e7a8c557215d85103813454

jobs:
  build_arch_linux_jack1:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Add pro-audio-legacy repository
        run: |
          printf "[pro-audio-legacy]\nServer = https://pkgbuild.com/~dvzrv/repos/pro-audio-legacy/\$arch\n" >> /etc/pacman.conf
          pacman -Syy
      - name: Install dependencies
        run: pacman --noconfirm -Syu alsa-lib base-devel jack meson opus readline libsamplerate libsndfile zita-alsa-pcmi zita-resampler
      - name: Build jack-example-tools
        run: meson build ${{ env.MESON_LINUX_BUILD_OPTS }} && ninja -C build
      - name: Install jack-example-tools
        run: ninja -C build install
  build_arch_linux_jack2:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pacman --noconfirm -Syu alsa-lib base-devel jack2 meson opus readline libsamplerate libsndfile zita-alsa-pcmi zita-resampler
      - name: Build jack-example-tools
        run: meson build ${{ env.MESON_LINUX_BUILD_OPTS }} && ninja -C build
      - name: Install jack-example-tools
        run: ninja -C build install
  build_arch_linux_pipewire_jack:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pacman --noconfirm -Syu alsa-lib base-devel meson opus pipewire-jack readline libsamplerate libsndfile zita-alsa-pcmi zita-resampler
      - name: Build jack-example-tools
        run: meson build ${{ env.MESON_LINUX_BUILD_OPTS }} && ninja -C build
      - name: Install jack-example-tools
        run: ninja -C build install
  build_alpine_linux:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: apk add g++ meson pkgconf alsa-lib-dev jack-dev opus-dev readline-dev libsamplerate-dev libsndfile-dev
      - name: Build jack-example-tools
        run: meson build ${{ env.MESON_LINUX_BUILD_OPTS }} && ninja -C build
      - name: Install jack-example-tools
        run: ninja -C build install
